/**
 * Morning Briefing — the card at the top of the Dashboard that greets
 * the agent by name and tells them what to do today. Generated once per
 * day per agent by the `pulse-generate-briefing` edge function, cached
 * in `pulse_briefings`, dismissible.
 *
 * Failure mode: if the edge function returns nothing (AI off, error,
 * no key, etc.) the component renders nothing at all. Never blocks the
 * rest of the Dashboard from loading.
 */

import React from 'react';
import { Sparkles, X, Loader2, Sunrise, RefreshCw } from 'lucide-react';
import { usePulseBriefing } from '../hooks/usePulseBriefing';

interface MorningBriefingProps {
  agentId: string | null | undefined;
  agentName: string | undefined;
  /** Admin-only: shows a "Regenerate" button that bypasses the cache. */
  canRegenerate?: boolean;
}

export const MorningBriefing: React.FC<MorningBriefingProps> = ({
  agentId,
  agentName,
  canRegenerate = false,
}) => {
  const { briefing, loading, generating, dismiss, regenerate } =
    usePulseBriefing(agentId, agentName);

  // No agent selected (admin whole-team view) — render nothing.
  if (!agentId) return null;

  // Already dismissed today — render nothing.
  if (briefing?.read_at) return null;

  // Loading / generating state
  if (loading || generating) {
    return (
      <div className="relative rounded-2xl border border-brand-500/20 bg-gradient-to-br from-brand-500/5 to-indigo-500/5 p-5 overflow-hidden animate-fade-in">
        <div className="absolute top-0 right-0 w-64 h-32 bg-brand-500/10 blur-[80px] pointer-events-none" />
        <div className="relative flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-brand-500/10 border border-brand-500/20">
            <Sunrise size={16} className="text-brand-400" />
          </div>
          <div className="flex items-center gap-2 text-muted text-xs">
            <Loader2 size={12} className="animate-spin" />
            {generating
              ? 'Coach is writing your morning briefing…'
              : 'Loading briefing…'}
          </div>
        </div>
      </div>
    );
  }

  // No briefing available (AI off, error, etc.) — render nothing.
  if (!briefing) return null;

  const isAi =
    briefing.meta != null &&
    typeof briefing.meta === 'object' &&
    (briefing.meta as Record<string, unknown>).generated_via === 'anthropic_haiku_4_5';

  return (
    <div className="relative rounded-2xl border border-brand-500/20 bg-gradient-to-br from-brand-500/10 via-indigo-500/5 to-transparent p-5 overflow-hidden animate-fade-in group">
      {/* Ambient glow */}
      <div className="absolute -top-8 -right-8 w-64 h-64 bg-brand-500/10 blur-[100px] pointer-events-none opacity-80" />
      <div className="absolute -bottom-12 left-8 w-48 h-48 bg-indigo-500/10 blur-[80px] pointer-events-none opacity-60" />

      {/* Header */}
      <div className="relative flex items-start justify-between gap-3 mb-3">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-brand-500/15 border border-brand-500/30">
            <Sunrise size={16} className="text-brand-300" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-[10px] font-black uppercase tracking-widest text-brand-300">
                Morning Briefing
              </h3>
              {isAi && (
                <span
                  className="inline-flex items-center gap-1 text-[9px] font-black uppercase tracking-widest px-1.5 py-0.5 rounded bg-brand-500/10 border border-brand-500/20 text-brand-400"
                  title="AI-generated by Pulse (Haiku 4.5) using your active Playbook"
                >
                  <Sparkles size={9} />
                  AI
                </span>
              )}
            </div>
            <p className="text-[10px] text-muted mt-0.5">
              {new Date(briefing.for_date).toLocaleDateString([], {
                weekday: 'long',
                month: 'short',
                day: 'numeric',
              })}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-1">
          {canRegenerate && (
            <button
              onClick={() => void regenerate()}
              disabled={generating}
              className="p-1.5 rounded-lg text-muted hover:text-brand-400 hover:bg-brand-500/10 transition-all opacity-0 group-hover:opacity-100 focus:opacity-100 disabled:opacity-40"
              title="Regenerate briefing from scratch (admin only)"
            >
              <RefreshCw size={13} className={generating ? 'animate-spin' : ''} />
            </button>
          )}
          <button
            onClick={() => void dismiss()}
            className="p-1.5 rounded-lg text-muted hover:text-white hover:bg-white/5 transition-all opacity-0 group-hover:opacity-100 focus:opacity-100"
            title="Dismiss until tomorrow"
          >
            <X size={14} />
          </button>
        </div>
      </div>

      {/* Body */}
      <p className="relative text-sm text-gray-200 leading-relaxed whitespace-pre-wrap">
        {briefing.body_md}
      </p>
    </div>
  );
};
