/**
 * A single row in the Pulse feed. Compact two-line layout:
 *
 *   Line 1: [status] Name · badge · agent · [Act →]
 *   Line 2: AI one-liner (truncated to one line with ellipsis)
 *
 * Line 1 fixed at ~20px, Line 2 at ~18px + tight padding → ~50px per row,
 * roughly 2x denser than the old three-line layout. The "last note"
 * snippet was removed because it's duplicated in the detail modal and
 * the AI narrative already references the relevant note context.
 *
 * AI narratives override the deterministic fallback when present via
 * item.ai_title / item.ai_body (populated by usePulseFeed after the
 * edge function round-trip).
 */

import React from 'react';
import { ArrowRight, Sparkles } from 'lucide-react';
import type { PulseFeedItem } from '../types/pulse.types';
import { formatSignalBadge, formatNarrative } from '../lib/categorize';

interface PulseItemProps {
  item: PulseFeedItem;
  onOpen: (leadId: string) => void;
  showAgent?: boolean;
}

export const PulseItem: React.FC<PulseItemProps> = ({ item, onOpen, showAgent }) => {
  const isAi = Boolean(item.ai_body);
  const narrative = item.ai_body || formatNarrative(item);
  const badge = formatSignalBadge(item);
  const fullTooltip = narrative; // full text on hover for truncated one-liners

  return (
    <div
      onClick={() => onOpen(item.lead_id)}
      className="group flex items-center gap-3 px-4 py-2 hover:bg-white/[0.02] border-b border-white/5 transition-colors cursor-pointer h-full"
    >
      <div className="flex-1 min-w-0">
        {/* Line 1: identity + signal */}
        <div className="flex items-center gap-2 min-w-0">
          <StatusPill status={item.status} />
          <span className="text-sm font-bold text-white truncate group-hover:text-brand-400 transition-colors">
            {isAi && item.ai_title ? item.ai_title : item.lead_name}
          </span>
          {isAi && item.ai_title && (
            <span className="text-[10px] text-muted/70 truncate">· {item.lead_name}</span>
          )}
          {badge && (
            <span className="shrink-0 text-[9px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded bg-white/5 text-muted">
              {badge}
            </span>
          )}
          {showAgent && item.agent_name && (
            <span className="shrink-0 text-[9px] font-bold uppercase text-muted">
              · {item.agent_name}
            </span>
          )}
          {isAi && (
            <Sparkles
              size={10}
              className="shrink-0 text-brand-400"
              aria-label="AI-generated by Pulse"
            />
          )}
        </div>

        {/* Line 2: single-line narrative with hover tooltip for full text */}
        {narrative && (
          <p
            title={fullTooltip}
            className={`text-xs leading-snug truncate mt-0.5 ${
              isAi ? 'text-gray-300' : 'text-gray-400'
            }`}
          >
            {narrative}
          </p>
        )}
      </div>

      {/* Act button — hover-reveal on desktop, always visible on focus */}
      <button
        onClick={(e) => {
          e.stopPropagation();
          onOpen(item.lead_id);
        }}
        className="shrink-0 flex items-center gap-1 px-2.5 py-1 bg-brand-500/10 hover:bg-brand-500/20 border border-brand-500/20 rounded text-[9px] font-black uppercase tracking-widest text-brand-400 transition-all opacity-0 group-hover:opacity-100 focus:opacity-100"
        aria-label={`Open ${item.lead_name}`}
      >
        Act
        <ArrowRight size={9} />
      </button>
    </div>
  );
};

const statusColors: Record<string, string> = {
  hot:         'bg-red-500/10 text-red-400 border-red-500/20',
  warm:        'bg-amber-500/10 text-amber-400 border-amber-500/20',
  progressive: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
  cold:        'bg-blue-500/10 text-blue-400 border-blue-500/20',
  sold:        'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
  closed:      'bg-white/5 text-muted border-white/10',
};

const StatusPill: React.FC<{ status: string }> = ({ status }) => (
  <span
    className={`shrink-0 text-[8px] font-black uppercase tracking-widest px-1.5 py-0.5 rounded border ${
      statusColors[status] || statusColors.closed
    }`}
  >
    {status}
  </span>
);
